### ISSUE TITLE
Make a tag for JASP 0.12 release

### ISSUE THREAD

**Issue by JorisGoosen** [AlexanderLyNL/bstats#1]
Maybe it would be nice if there was a tag in this repo that tells us which version was(/should be) used in JASP 0.12?

I will now just take the current commit for flatpak inclusion.

**Comment by AlexanderLyNL** [comment]
Done for v0.0.1. Needs checking with JASP.

**Comment by AlexanderLyNL** [comment]
git tag -a v0.0.1 -m "someMessage:
git push -u origin v0.0.1
